spring:
  application:
    name: BookTracker
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  logging:
    level:
      root: INFO
      org.springframework: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:5434/books
    username: postgresql
    password: mysecretpassword

  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.yandex.ru
    port: 587
    username: lorestatys@yandex.ru
    password: adkitypqxwowwzyl
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: false

  weather:
    api_key: 1ec6cf431130ab693b7792bad21c8370
    base_url: https://api.openweathermap.org/data/2.5/weather

