spring:
  application:
    name: BookTracker

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

#  cache:
#    type: redis
#  data:
#    redis:
#      host: localhost
#      port: 6379

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,caches
    metrics:
      enable:
        redis: true

  logging:
    level:
      root: INFO
      org.springframework: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:5434/books
    username: postgresql
    password: mysecretpassword

  devtools:
    restart:
      enabled: false

  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.yandex.ru
    port: 587
    username: lorestatys@yandex.ru
    password: adkitypqxwowwzyl
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.enable: false

  weather:
    service:
      url: http://localhost:8081

  google-books:
    service:
      url: http://localhost:8082

  post:
    service:
      url: http://localhost:8083
